CREATE TABLE employee (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          name VARCHAR(150) NOT NULL,
                          role VARCHAR(100),
                          salary NUMERIC(12,2) CHECK (salary >= 0),

                          username VARCHAR(100) NOT NULL UNIQUE,
                          password_hash VARCHAR(255) NOT NULL,

                          active BOOLEAN NOT NULL DEFAULT TRUE,

                          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP
);

CREATE INDEX idx_employee_username ON employee(username);