-- =========================
-- CUSTOMER
-- =========================
CREATE TABLE customer (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          name VARCHAR(150) NOT NULL,
                          email VARCHAR(150),
                          phone VARCHAR(20),
                          document VARCHAR(20),

                          active BOOLEAN NOT NULL DEFAULT TRUE,

                          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP
);

CREATE INDEX idx_customer_document ON customer(document);
CREATE INDEX idx_customer_email ON customer(email);



-- =========================
-- PRODUCT
-- =========================
CREATE TABLE product (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         name VARCHAR(150) NOT NULL,
                         description VARCHAR(500),
                         brand VARCHAR(100),

                         price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
                         stock_quantity INT NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),

                         active BOOLEAN NOT NULL DEFAULT TRUE,

                         created_by BIGINT,

                         created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP,

                         CONSTRAINT fk_product_created_by
                             FOREIGN KEY (created_by)
                                 REFERENCES employee(id)
                                 ON DELETE SET NULL
);

CREATE INDEX idx_product_name ON product(name);



-- =========================
-- SALE
-- =========================
CREATE TABLE sale (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                      customer_id BIGINT NOT NULL,
                      employee_id BIGINT NOT NULL,

                      sale_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                      total_amount NUMERIC(14,2) NOT NULL CHECK (total_amount >= 0),

                      payment_method VARCHAR(50) NOT NULL,

                      status VARCHAR(20) NOT NULL,

                      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                      CONSTRAINT chk_sale_status
                          CHECK (status IN ('OPEN', 'COMPLETED', 'CANCELLED')),

                      CONSTRAINT fk_sale_customer
                          FOREIGN KEY (customer_id)
                              REFERENCES customer(id),

                      CONSTRAINT fk_sale_employee
                          FOREIGN KEY (employee_id)
                              REFERENCES employee(id)
);

CREATE INDEX idx_sale_customer ON sale(customer_id);
CREATE INDEX idx_sale_date ON sale(sale_date);



-- =========================
-- SALE_ITEM
-- =========================
CREATE TABLE sale_item (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                           sale_id BIGINT NOT NULL,
                           product_id BIGINT NOT NULL,

                           quantity INT NOT NULL CHECK (quantity > 0),
                           unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),

                           subtotal NUMERIC(14,2) GENERATED ALWAYS AS
                               (quantity * unit_price) STORED,

                           CONSTRAINT fk_sale_item_sale
                               FOREIGN KEY (sale_id)
                                   REFERENCES sale(id)
                                   ON DELETE CASCADE,

                           CONSTRAINT fk_sale_item_product
                               FOREIGN KEY (product_id)
                                   REFERENCES product(id)
);

CREATE INDEX idx_sale_item_sale ON sale_item(sale_id);



-- =========================
-- STOCK_MOVEMENT
-- =========================
CREATE TABLE stock_movement (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                product_id BIGINT NOT NULL,
                                employee_id BIGINT NOT NULL,

                                movement_type VARCHAR(20) NOT NULL,
                                quantity INT NOT NULL CHECK (quantity > 0),

                                movement_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                CONSTRAINT chk_stock_movement_type
                                    CHECK (movement_type IN ('IN', 'OUT', 'ADJUSTMENT')),

                                CONSTRAINT fk_stock_product
                                    FOREIGN KEY (product_id)
                                        REFERENCES product(id),

                                CONSTRAINT fk_stock_employee
                                    FOREIGN KEY (employee_id)
                                        REFERENCES employee(id)
);

CREATE INDEX idx_stock_product ON stock_movement(product_id);
CREATE INDEX idx_stock_date ON stock_movement(movement_date);
